### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by jepunband** [Ataaoo/DecrypTool#2]
python3 DecrypTool.py -c

Traceback (most recent call last):
  File "/home/user/DecrypTool/DecrypTool.py", line 9, in <module>
    from librairies.Rsa_files.RSA import Rsa
  File "/home/user/DecrypTool/librairies/Rsa_files/RSA.py", line 3, in <module>
    from Crypto.PublicKey import RSA
  File "/usr/local/lib/python3.9/dist-packages/Crypto/PublicKey/RSA.py", line 585
    except ValueError, IndexError:
                     ^
SyntaxError: invalid syntax

**Comment by Ataaoo** [comment]
Hi, i'm trying to fix it, but can't re create the error. Are you sure that you have all the libriaries installed ?

**Comment by jepunband** [comment]
yes. i have installed using this : pip3 install -r "requirement.txt"
